alias chrmdbg="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222"
alias editzsh="$EDITOR ~/.zshrc"
alias grep="grep --color=auto"
alias ls="colorls"
alias nvidia-update="bash <(curl -s https://raw.githubusercontent.com/Benjamin-Dobell/nvidia-update/master/nvidia-update.sh)"
alias rldzsh="source ~/.zshrc"
alias rna="react-native run-android"
alias rni="react-native run-ios"
alias tm="tmux"
alias top="vtop --theme=parallax"
alias vim="nvim"
alias v="nvim"
alias vi="/usr/bin/vim"
alias weather="curl v2.wttr.in"
alias brvdbg="/Applications/Brave\ Browser\ Dev.app/Contents/MacOS/Brave\ Browser\ Dev --remote-debugging-port=9222"
alias co="code ."
alias cup="cd .."
alias lg="lazygit"

source $HOME/.oh-my-zsh/custom/plugins/pnpm/pnpm.plugin.zsh
